name: api_petvida
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2+1
    
  http: ^1.2.1

  dio: ^5.0.0

  shared_preferences: ^2.2.0

  cupertino_icons: ^1.0.8

  firebase_core: ^2.24.2 # Use a versão estável mais recente
  
  firebase_messaging: ^14.7.12 # Use a versão estável mais recente
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  